# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/tip_gui_cover.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(669, 755)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 44))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tip_url = QtWidgets.QLineEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tip_url.sizePolicy().hasHeightForWidth())
        self.tip_url.setSizePolicy(sizePolicy)
        self.tip_url.setMinimumSize(QtCore.QSize(0, 10))
        self.tip_url.setObjectName("tip_url")
        self.gridLayout_2.addWidget(self.tip_url, 0, 1, 1, 1)
        self.Start = QtWidgets.QPushButton(self.groupBox_3)
        self.Start.setCheckable(True)
        self.Start.setAutoDefault(False)
        self.Start.setDefault(False)
        self.Start.setFlat(False)
        self.Start.setObjectName("Start")
        self.gridLayout_2.addWidget(self.Start, 0, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 5, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.Connect = QtWidgets.QPushButton(self.groupBox_3)
        self.Connect.setCheckable(True)
        self.Connect.setObjectName("Connect")
        self.gridLayout_2.addWidget(self.Connect, 0, 2, 1, 1)
        self.Quit = QtWidgets.QPushButton(self.groupBox_3)
        self.Quit.setEnabled(True)
        self.Quit.setObjectName("Quit")
        self.gridLayout_2.addWidget(self.Quit, 0, 4, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 110))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.Interval = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.Interval.setEnabled(True)
        self.Interval.setFrame(True)
        self.Interval.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.Interval.setDecimals(2)
        self.Interval.setMaximum(10000.0)
        self.Interval.setObjectName("Interval")
        self.gridLayout.addWidget(self.Interval, 1, 4, 1, 1)
        self.T_field = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.T_field.setAutoFillBackground(False)
        self.T_field.setFrame(False)
        self.T_field.setReadOnly(True)
        self.T_field.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.T_field.setDecimals(5)
        self.T_field.setMaximum(999.9)
        self.T_field.setObjectName("T_field")
        self.gridLayout.addWidget(self.T_field, 0, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 2, 1, 1)
        self.excitation_spinbox = QtWidgets.QSpinBox(self.groupBox)
        self.excitation_spinbox.setSuffix("")
        self.excitation_spinbox.setObjectName("excitation_spinbox")
        self.gridLayout.addWidget(self.excitation_spinbox, 1, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.Thermometer_box = QtWidgets.QComboBox(self.groupBox)
        self.Thermometer_box.setObjectName("Thermometer_box")
        self.gridLayout.addWidget(self.Thermometer_box, 0, 1, 1, 1)
        self.R_field = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.R_field.setFrame(False)
        self.R_field.setReadOnly(True)
        self.R_field.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.R_field.setDecimals(4)
        self.R_field.setMaximum(10000000.0)
        self.R_field.setObjectName("R_field")
        self.gridLayout.addWidget(self.R_field, 0, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.range_spinbox = QtWidgets.QSpinBox(self.groupBox)
        self.range_spinbox.setSuffix("")
        self.range_spinbox.setObjectName("range_spinbox")
        self.gridLayout.addWidget(self.range_spinbox, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.I_SpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.I_SpinBox.setKeyboardTracking(False)
        self.I_SpinBox.setDecimals(6)
        self.I_SpinBox.setSingleStep(0.001)
        self.I_SpinBox.setObjectName("I_SpinBox")
        self.gridLayout_3.addWidget(self.I_SpinBox, 1, 1, 1, 1)
        self.P_SpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.P_SpinBox.sizePolicy().hasHeightForWidth())
        self.P_SpinBox.setSizePolicy(sizePolicy)
        self.P_SpinBox.setKeyboardTracking(False)
        self.P_SpinBox.setDecimals(6)
        self.P_SpinBox.setSingleStep(0.001)
        self.P_SpinBox.setObjectName("P_SpinBox")
        self.gridLayout_3.addWidget(self.P_SpinBox, 1, 0, 1, 1)
        self.newT_SpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.newT_SpinBox.setKeyboardTracking(False)
        self.newT_SpinBox.setDecimals(4)
        self.newT_SpinBox.setMaximum(300.0)
        self.newT_SpinBox.setSingleStep(0.001)
        self.newT_SpinBox.setObjectName("newT_SpinBox")
        self.gridLayout_3.addWidget(self.newT_SpinBox, 1, 3, 1, 1)
        self.D_SpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.D_SpinBox.setKeyboardTracking(False)
        self.D_SpinBox.setDecimals(6)
        self.D_SpinBox.setSingleStep(0.001)
        self.D_SpinBox.setObjectName("D_SpinBox")
        self.gridLayout_3.addWidget(self.D_SpinBox, 1, 2, 1, 1)
        self.H_field = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.H_field.setFrame(False)
        self.H_field.setReadOnly(True)
        self.H_field.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.H_field.setDecimals(4)
        self.H_field.setObjectName("H_field")
        self.gridLayout_3.addWidget(self.H_field, 1, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 1, 5, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 4, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 0, 5, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.Temp_view = PlotWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Temp_view.sizePolicy().hasHeightForWidth())
        self.Temp_view.setSizePolicy(sizePolicy)
        self.Temp_view.setObjectName("Temp_view")
        self.verticalLayout.addWidget(self.Temp_view)
        self.Heat_view = PlotWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Heat_view.sizePolicy().hasHeightForWidth())
        self.Heat_view.setSizePolicy(sizePolicy)
        self.Heat_view.setObjectName("Heat_view")
        self.verticalLayout.addWidget(self.Heat_view)
        self.Error_view = PlotWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Error_view.sizePolicy().hasHeightForWidth())
        self.Error_view.setSizePolicy(sizePolicy)
        self.Error_view.setObjectName("Error_view")
        self.verticalLayout.addWidget(self.Error_view)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 669, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuControl = QtWidgets.QMenu(self.menubar)
        self.menuControl.setObjectName("menuControl")
        self.menuTIP = QtWidgets.QMenu(self.menuControl)
        self.menuTIP.setObjectName("menuTIP")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAll_Devices = QtWidgets.QAction(MainWindow)
        self.actionAll_Devices.setObjectName("actionAll_Devices")
        self.action_TIP_server = QtWidgets.QAction(MainWindow)
        self.action_TIP_server.setObjectName("action_TIP_server")
        self.actionQuit_TG = QtWidgets.QAction(MainWindow)
        self.actionQuit_TG.setObjectName("actionQuit_TG")
        self.actionTIP_Configuration = QtWidgets.QAction(MainWindow)
        self.actionTIP_Configuration.setObjectName("actionTIP_Configuration")
        self.actionQuit_TIP_GUI = QtWidgets.QAction(MainWindow)
        self.actionQuit_TIP_GUI.setObjectName("actionQuit_TIP_GUI")
        self.actionQuit_TIP_server = QtWidgets.QAction(MainWindow)
        self.actionQuit_TIP_server.setObjectName("actionQuit_TIP_server")
        self.actionreconnect_to_TIP = QtWidgets.QAction(MainWindow)
        self.actionreconnect_to_TIP.setObjectName("actionreconnect_to_TIP")
        self.menuFile.addAction(self.actionQuit)
        self.menuView.addAction(self.actionAll_Devices)
        self.menuView.addAction(self.actionTIP_Configuration)
        self.menuTIP.addAction(self.actionQuit_TIP_server)
        self.menuControl.addAction(self.action_TIP_server)
        self.menuControl.addSeparator()
        self.menuControl.addAction(self.menuTIP.menuAction())
        self.menuControl.addSeparator()
        self.menuControl.addAction(self.actionQuit_TIP_GUI)
        self.menuControl.addSeparator()
        self.menuControl.addAction(self.actionreconnect_to_TIP)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuControl.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TIP"))
        self.tip_url.setText(_translate("MainWindow", "tcp://localhost:5000"))
        self.Start.setText(_translate("MainWindow", "Start"))
        self.label.setText(_translate("MainWindow", "TIP:"))
        self.Connect.setText(_translate("MainWindow", "Connect"))
        self.Quit.setText(_translate("MainWindow", "Quit"))
        self.groupBox.setTitle(_translate("MainWindow", "Temperature"))
        self.Interval.setPrefix(_translate("MainWindow", "Interval: "))
        self.Interval.setSuffix(_translate("MainWindow", "s"))
        self.T_field.setPrefix(_translate("MainWindow", "T: "))
        self.T_field.setSuffix(_translate("MainWindow", " K"))
        self.label_4.setText(_translate("MainWindow", "Excitation"))
        self.label_6.setText(_translate("MainWindow", "Current"))
        self.label_2.setText(_translate("MainWindow", "Thermometer"))
        self.R_field.setPrefix(_translate("MainWindow", "R: "))
        self.R_field.setSuffix(_translate("MainWindow", " Ohm"))
        self.label_3.setText(_translate("MainWindow", "Range"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Control"))
        self.I_SpinBox.setPrefix(_translate("MainWindow", "I: "))
        self.P_SpinBox.setPrefix(_translate("MainWindow", "P: "))
        self.newT_SpinBox.setPrefix(_translate("MainWindow", "T: "))
        self.newT_SpinBox.setSuffix(_translate("MainWindow", " K"))
        self.D_SpinBox.setPrefix(_translate("MainWindow", "D: "))
        self.H_field.setPrefix(_translate("MainWindow", "Heat: "))
        self.H_field.setSuffix(_translate("MainWindow", " uW"))
        self.label_7.setText(_translate("MainWindow", "Current:"))
        self.label_5.setText(_translate("MainWindow", "New: "))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuControl.setTitle(_translate("MainWindow", "Control"))
        self.menuTIP.setTitle(_translate("MainWindow", "TIP"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionAll_Devices.setText(_translate("MainWindow", "All Active Devices"))
        self.action_TIP_server.setText(_translate("MainWindow", "connect to TIP server"))
        self.actionQuit_TG.setText(_translate("MainWindow", "Quit TIP GUI"))
        self.actionTIP_Configuration.setText(_translate("MainWindow", "TIP Configuration"))
        self.actionQuit_TIP_GUI.setText(_translate("MainWindow", "Quit TIP GUI"))
        self.actionQuit_TIP_server.setText(_translate("MainWindow", "Quit TIP server"))
        self.actionreconnect_to_TIP.setText(_translate("MainWindow", "reconnect to TIP"))
from pyqtgraph import PlotWidget
