# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tip_gui_cover.ui'
#
# Created: Wed May 13 12:11:01 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(586, 726)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.Quit = QtGui.QPushButton(self.centralwidget)
        self.Quit.setEnabled(True)
        self.Quit.setGeometry(QtCore.QRect(520, 100, 61, 31))
        self.Quit.setObjectName(_fromUtf8("Quit"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 110, 16, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(170, 110, 16, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(310, 110, 16, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 50, 61, 20))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 571, 81))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.newT_SpinBox = QtGui.QDoubleSpinBox(self.groupBox)
        self.newT_SpinBox.setGeometry(QtCore.QRect(80, 50, 111, 24))
        self.newT_SpinBox.setKeyboardTracking(False)
        self.newT_SpinBox.setDecimals(4)
        self.newT_SpinBox.setMaximum(300.0)
        self.newT_SpinBox.setSingleStep(0.001)
        self.newT_SpinBox.setObjectName(_fromUtf8("newT_SpinBox"))
        self.T_field = QtGui.QDoubleSpinBox(self.groupBox)
        self.T_field.setGeometry(QtCore.QRect(80, 20, 91, 24))
        self.T_field.setAutoFillBackground(False)
        self.T_field.setFrame(False)
        self.T_field.setReadOnly(True)
        self.T_field.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.T_field.setDecimals(4)
        self.T_field.setObjectName(_fromUtf8("T_field"))
        self.R_field = QtGui.QDoubleSpinBox(self.groupBox)
        self.R_field.setGeometry(QtCore.QRect(180, 20, 131, 24))
        self.R_field.setFrame(False)
        self.R_field.setReadOnly(True)
        self.R_field.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.R_field.setDecimals(3)
        self.R_field.setMaximum(10000000.0)
        self.R_field.setObjectName(_fromUtf8("R_field"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(20, 20, 61, 20))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.H_field = QtGui.QDoubleSpinBox(self.groupBox)
        self.H_field.setGeometry(QtCore.QRect(330, 20, 121, 24))
        self.H_field.setFrame(False)
        self.H_field.setReadOnly(True)
        self.H_field.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.H_field.setDecimals(4)
        self.H_field.setObjectName(_fromUtf8("H_field"))
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 80, 451, 51))
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.P_SpinBox = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.P_SpinBox.setGeometry(QtCore.QRect(30, 20, 121, 24))
        self.P_SpinBox.setKeyboardTracking(False)
        self.P_SpinBox.setDecimals(6)
        self.P_SpinBox.setSingleStep(0.001)
        self.P_SpinBox.setObjectName(_fromUtf8("P_SpinBox"))
        self.I_SpinBox = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.I_SpinBox.setGeometry(QtCore.QRect(170, 20, 111, 24))
        self.I_SpinBox.setKeyboardTracking(False)
        self.I_SpinBox.setDecimals(6)
        self.I_SpinBox.setSingleStep(0.001)
        self.I_SpinBox.setObjectName(_fromUtf8("I_SpinBox"))
        self.D_SpinBox = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.D_SpinBox.setGeometry(QtCore.QRect(320, 20, 101, 24))
        self.D_SpinBox.setKeyboardTracking(False)
        self.D_SpinBox.setDecimals(6)
        self.D_SpinBox.setSingleStep(0.001)
        self.D_SpinBox.setObjectName(_fromUtf8("D_SpinBox"))
        self.Start = QtGui.QPushButton(self.centralwidget)
        self.Start.setGeometry(QtCore.QRect(460, 100, 61, 31))
        self.Start.setCheckable(True)
        self.Start.setAutoDefault(False)
        self.Start.setDefault(False)
        self.Start.setFlat(False)
        self.Start.setObjectName(_fromUtf8("Start"))
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(10, 140, 561, 541))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.Temp_view = PlotWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Temp_view.sizePolicy().hasHeightForWidth())
        self.Temp_view.setSizePolicy(sizePolicy)
        self.Temp_view.setObjectName(_fromUtf8("Temp_view"))
        self.Heat_view = PlotWidget(self.splitter)
        self.Heat_view.setObjectName(_fromUtf8("Heat_view"))
        self.Error_view = PlotWidget(self.splitter)
        self.Error_view.setObjectName(_fromUtf8("Error_view"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 586, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.Quit, self.Temp_view)
        MainWindow.setTabOrder(self.Temp_view, self.Heat_view)
        MainWindow.setTabOrder(self.Heat_view, self.Error_view)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "TIP", None))
        self.Quit.setText(_translate("MainWindow", "Quit", None))
        self.label.setText(_translate("MainWindow", "P", None))
        self.label_2.setText(_translate("MainWindow", "I", None))
        self.label_3.setText(_translate("MainWindow", "D", None))
        self.label_5.setText(_translate("MainWindow", "new: ", None))
        self.groupBox.setTitle(_translate("MainWindow", "Temperature", None))
        self.newT_SpinBox.setPrefix(_translate("MainWindow", "T: ", None))
        self.newT_SpinBox.setSuffix(_translate("MainWindow", " K", None))
        self.T_field.setPrefix(_translate("MainWindow", "T: ", None))
        self.T_field.setSuffix(_translate("MainWindow", " K", None))
        self.R_field.setPrefix(_translate("MainWindow", "R: ", None))
        self.R_field.setSuffix(_translate("MainWindow", " Ohm", None))
        self.label_4.setText(_translate("MainWindow", "current", None))
        self.H_field.setPrefix(_translate("MainWindow", "Heat: ", None))
        self.H_field.setSuffix(_translate("MainWindow", " uW", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Control", None))
        self.Start.setText(_translate("MainWindow", "Start", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))

from pyqtgraph import PlotWidget
