# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'minimal_gui\tip_gui_cover.ui'
#
# Created: Fri Dec 04 10:23:42 2015
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(897, 613)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.Temp_view2 = PlotWidget(self.centralwidget)
        self.Temp_view2.setGeometry(QtCore.QRect(450, 10, 431, 181))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Temp_view2.sizePolicy().hasHeightForWidth())
        self.Temp_view2.setSizePolicy(sizePolicy)
        self.Temp_view2.setObjectName(_fromUtf8("Temp_view2"))
        self.Temp_view3 = PlotWidget(self.centralwidget)
        self.Temp_view3.setGeometry(QtCore.QRect(10, 200, 431, 181))
        self.Temp_view3.setObjectName(_fromUtf8("Temp_view3"))
        self.Temp_view1 = PlotWidget(self.centralwidget)
        self.Temp_view1.setGeometry(QtCore.QRect(10, 10, 431, 181))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Temp_view1.sizePolicy().hasHeightForWidth())
        self.Temp_view1.setSizePolicy(sizePolicy)
        self.Temp_view1.setObjectName(_fromUtf8("Temp_view1"))
        self.Temp_view5 = PlotWidget(self.centralwidget)
        self.Temp_view5.setGeometry(QtCore.QRect(450, 200, 431, 181))
        self.Temp_view5.setObjectName(_fromUtf8("Temp_view5"))
        self.Temp_view4 = PlotWidget(self.centralwidget)
        self.Temp_view4.setGeometry(QtCore.QRect(10, 390, 871, 181))
        self.Temp_view4.setObjectName(_fromUtf8("Temp_view4"))
        self.T2_field = QtGui.QDoubleSpinBox(self.centralwidget)
        self.T2_field.setGeometry(QtCore.QRect(650, 20, 221, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.T2_field.sizePolicy().hasHeightForWidth())
        self.T2_field.setSizePolicy(sizePolicy)
        self.T2_field.setSizeIncrement(QtCore.QSize(0, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.T2_field.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(23)
        self.T2_field.setFont(font)
        self.T2_field.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.T2_field.setAutoFillBackground(False)
        self.T2_field.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.T2_field.setFrame(False)
        self.T2_field.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.T2_field.setReadOnly(True)
        self.T2_field.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.T2_field.setDecimals(2)
        self.T2_field.setMaximum(1000.0)
        self.T2_field.setProperty("value", 0.0)
        self.T2_field.setObjectName(_fromUtf8("T2_field"))
        self.T3_field = QtGui.QDoubleSpinBox(self.centralwidget)
        self.T3_field.setGeometry(QtCore.QRect(210, 210, 221, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.T3_field.sizePolicy().hasHeightForWidth())
        self.T3_field.setSizePolicy(sizePolicy)
        self.T3_field.setSizeIncrement(QtCore.QSize(0, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.T3_field.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(23)
        self.T3_field.setFont(font)
        self.T3_field.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.T3_field.setAutoFillBackground(False)
        self.T3_field.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.T3_field.setFrame(False)
        self.T3_field.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.T3_field.setReadOnly(True)
        self.T3_field.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.T3_field.setDecimals(2)
        self.T3_field.setMaximum(1000.0)
        self.T3_field.setProperty("value", 0.0)
        self.T3_field.setObjectName(_fromUtf8("T3_field"))
        self.T5_field = QtGui.QDoubleSpinBox(self.centralwidget)
        self.T5_field.setGeometry(QtCore.QRect(650, 210, 221, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.T5_field.sizePolicy().hasHeightForWidth())
        self.T5_field.setSizePolicy(sizePolicy)
        self.T5_field.setSizeIncrement(QtCore.QSize(0, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.T5_field.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(23)
        self.T5_field.setFont(font)
        self.T5_field.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.T5_field.setAutoFillBackground(False)
        self.T5_field.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.T5_field.setFrame(False)
        self.T5_field.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.T5_field.setReadOnly(True)
        self.T5_field.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.T5_field.setDecimals(2)
        self.T5_field.setMaximum(1000.0)
        self.T5_field.setProperty("value", 0.0)
        self.T5_field.setObjectName(_fromUtf8("T5_field"))
        self.T4_field = QtGui.QDoubleSpinBox(self.centralwidget)
        self.T4_field.setGeometry(QtCore.QRect(650, 400, 221, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.T4_field.sizePolicy().hasHeightForWidth())
        self.T4_field.setSizePolicy(sizePolicy)
        self.T4_field.setSizeIncrement(QtCore.QSize(0, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.T4_field.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(23)
        self.T4_field.setFont(font)
        self.T4_field.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.T4_field.setAutoFillBackground(False)
        self.T4_field.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.T4_field.setFrame(False)
        self.T4_field.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.T4_field.setReadOnly(True)
        self.T4_field.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.T4_field.setDecimals(2)
        self.T4_field.setMaximum(1000.0)
        self.T4_field.setProperty("value", 0.0)
        self.T4_field.setObjectName(_fromUtf8("T4_field"))
        self.T1a_field = QtGui.QDoubleSpinBox(self.centralwidget)
        self.T1a_field.setGeometry(QtCore.QRect(200, 20, 231, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.T1a_field.sizePolicy().hasHeightForWidth())
        self.T1a_field.setSizePolicy(sizePolicy)
        self.T1a_field.setSizeIncrement(QtCore.QSize(0, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.T1a_field.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(23)
        self.T1a_field.setFont(font)
        self.T1a_field.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.T1a_field.setAutoFillBackground(False)
        self.T1a_field.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.T1a_field.setFrame(False)
        self.T1a_field.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.T1a_field.setReadOnly(True)
        self.T1a_field.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.T1a_field.setDecimals(2)
        self.T1a_field.setMaximum(1000.0)
        self.T1a_field.setProperty("value", 0.0)
        self.T1a_field.setObjectName(_fromUtf8("T1a_field"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 897, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuScale = QtGui.QMenu(self.menubar)
        self.menuScale.setObjectName(_fromUtf8("menuScale"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionStart = QtGui.QAction(MainWindow)
        self.actionStart.setObjectName(_fromUtf8("actionStart"))
        self.b_auto = QtGui.QAction(MainWindow)
        self.b_auto.setObjectName(_fromUtf8("b_auto"))
        self.b_24 = QtGui.QAction(MainWindow)
        self.b_24.setObjectName(_fromUtf8("b_24"))
        self.b_12 = QtGui.QAction(MainWindow)
        self.b_12.setObjectName(_fromUtf8("b_12"))
        self.b_6 = QtGui.QAction(MainWindow)
        self.b_6.setObjectName(_fromUtf8("b_6"))
        self.b_2 = QtGui.QAction(MainWindow)
        self.b_2.setObjectName(_fromUtf8("b_2"))
        self.b_1 = QtGui.QAction(MainWindow)
        self.b_1.setObjectName(_fromUtf8("b_1"))
        self.m_poll = QtGui.QAction(MainWindow)
        self.m_poll.setEnabled(False)
        self.m_poll.setObjectName(_fromUtf8("m_poll"))
        self.menuFile.addAction(self.m_poll)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionStart)
        self.menuFile.addAction(self.actionQuit)
        self.menuScale.addAction(self.b_auto)
        self.menuScale.addSeparator()
        self.menuScale.addAction(self.b_24)
        self.menuScale.addAction(self.b_12)
        self.menuScale.addAction(self.b_6)
        self.menuScale.addAction(self.b_2)
        self.menuScale.addAction(self.b_1)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuScale.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "TIP", None))
        self.T2_field.setPrefix(_translate("MainWindow", "T2: ", None))
        self.T2_field.setSuffix(_translate("MainWindow", " K", None))
        self.T3_field.setPrefix(_translate("MainWindow", "T3: ", None))
        self.T3_field.setSuffix(_translate("MainWindow", " K", None))
        self.T5_field.setPrefix(_translate("MainWindow", "T5: ", None))
        self.T5_field.setSuffix(_translate("MainWindow", " K", None))
        self.T4_field.setPrefix(_translate("MainWindow", "T4: ", None))
        self.T4_field.setSuffix(_translate("MainWindow", " K", None))
        self.T1a_field.setPrefix(_translate("MainWindow", "T1: ", None))
        self.T1a_field.setSuffix(_translate("MainWindow", " K", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuScale.setTitle(_translate("MainWindow", "Scale", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionStart.setText(_translate("MainWindow", "Start", None))
        self.b_auto.setText(_translate("MainWindow", "Autoscale", None))
        self.b_24.setText(_translate("MainWindow", "24h", None))
        self.b_12.setText(_translate("MainWindow", "12h", None))
        self.b_6.setText(_translate("MainWindow", "6h", None))
        self.b_2.setText(_translate("MainWindow", "2h", None))
        self.b_1.setText(_translate("MainWindow", "1h", None))
        self.m_poll.setText(_translate("MainWindow", "Measure all channels", None))

from pyqtgraph import PlotWidget
